name: MIL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - entmax==1.3
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - imgaug==0.4.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openai==0.28.0
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.13.0.90
      - packaging==26.0
      - pandas==2.3.3
      - pillow==12.1.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pynvml==11.5.3
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - sci-learn==0.1.4
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - stringzilla==4.6.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.24
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1a0
      - tqdm==4.67.1
      - transformers==4.45.2
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - yarl==1.22.0

